if (WIN32)

	target_compile_options(SoopStudio PRIVATE $<$<CONFIG:Release>:/FAcs>)
	
    set(STUDIO_EXE_MAP_NAME "SoopStudio.map")
    set(OBS_DLL_LIB_MAP_NAME "obs.map")
    set(OBS_DLL_D3D_MAP_NAME "libobs-d3d11.map")
    set(OBS_DLL_WINRT_NAME "libobs-winrt.map")
    set(OBS_PLUGINS_AJA_MAP_NAME "aja.map")
    set(OBS_PLUGINS_COREAUDIO_ENCODER_MAP_NAME "coreaudio-encoder.map")
    set(OBS_PLUGINS_DECKLINK_MAP_NAME "decklink.map")
    set(OBS_PLUGINS_IMAGE_SOURCE_MAP_NAME "image-source.map")
    set(OBS_PLUGINS_OBS_BROWSER_MAP_NAME "obs-browser.map")
    set(OBS_PLUGINS_OBS_FFMPEG_MAP_NAME "obs-ffmpeg.map")
    set(OBS_PLUGINS_OBS_FILTERS_MAP_NAME "obs-filters.map")
    set(OBS_PLUGINS_OBS_OUTPUTS_MAP_NAME "obs-outputs.map")
    set(OBS_PLUGINS_OBS_QSV11_MAP_NAME "obs-qsv11.map")
    set(OBS_PLUGINS_OBS_TEXT_MAP_NAME "obs-text.map")
    set(OBS_PLUGINS_OBS_TRANSITIONS_MAP_NAME "obs-transitions.map")
    set(OBS_PLUGINS_OBS_VST_MAP_NAME "obs-vst.map")
    set(OBS_PLUGINS_OBS_WEBRTC_MAP_NAME "obs-webrtc.map")
    set(OBS_PLUGINS_OBS_WEBSOCKET_MAP_NAME "obs-websocket.map")
    set(OBS_PLUGINS_OBS_X264_MAP_NAME "obs-x264.map")
    set(OBS_PLUGINS_RTMP_SERVICES_MAP_NAME "rtmp-services.map")
    set(OBS_PLUGINS_TEXT_FREETYPE2_MAP_NAME "text-freetype2.map")
    set(OBS_PLUGINS_VLC_VIDEO_MAP_NAME "vlc-video.map")
    set(OBS_PLUGINS_WIN_CAPTURE_MAP_NAME "win-capture.map")
    set(OBS_PLUGINS_WIN_DSHOW_MAP_NAME "win-dshow.map")
    set(OBS_PLUGINS_WIN_WASAPI_MAP_NAME "win-wasapi.map")
	set(COD_SOURCE_DIR "${CMAKE_BINARY_DIR}/SoopStudio.dir/$<CONFIG>")
    
    string(REPLACE "/" "\\" __OUT_MAP_FILES_DIR ${OUT_MAP_FILES_DIR})
    string(REPLACE "/" "\\" __STUDIO_EXE_MAP_DIR ${STUDIO_EXE_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_DLL_LIB_MAP_DIR ${OBS_DLL_LIB_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_DLL_D3D_MAP_DIR ${OBS_DLL_D3D_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_DLL_WINRT_DIR ${OBS_DLL_WINRT_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_AJA_MAP_DIR ${OBS_PLUGINS_AJA_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_COREAUDIO_ENCODER_MAP_DIR ${OBS_PLUGINS_COREAUDIO_ENCODER_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_DECKLINK_MAP_DIR ${OBS_PLUGINS_DECKLINK_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_IMAGE_SOURCE_MAP_DIR ${OBS_PLUGINS_IMAGE_SOURCE_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_BROWSER_MAP_DIR ${OBS_PLUGINS_OBS_BROWSER_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_FFMPEG_MAP_DIR ${OBS_PLUGINS_OBS_FFMPEG_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_FILTERS_MAP_DIR ${OBS_PLUGINS_OBS_FILTERS_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_OUTPUTS_MAP_DIR ${OBS_PLUGINS_OBS_OUTPUTS_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_QSV11_MAP_DIR ${OBS_PLUGINS_OBS_QSV11_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_TEXT_MAP_DIR ${OBS_PLUGINS_OBS_TEXT_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_TRANSITIONS_MAP_DIR ${OBS_PLUGINS_OBS_TRANSITIONS_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_VST_MAP_DIR ${OBS_PLUGINS_OBS_VST_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_WEBRTC_MAP_DIR ${OBS_PLUGINS_OBS_WEBRTC_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_WEBSOCKET_MAP_DIR ${OBS_PLUGINS_OBS_WEBSOCKET_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_OBS_X264_MAP_DIR ${OBS_PLUGINS_OBS_X264_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_RTMP_SERVICES_MAP_DIR ${OBS_PLUGINS_RTMP_SERVICES_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_TEXT_FREETYPE2_MAP_DIR ${OBS_PLUGINS_TEXT_FREETYPE2_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_VLC_VIDEO_MAP_DIR ${OBS_PLUGINS_VLC_VIDEO_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_WIN_CAPTURE_MAP_DIR ${OBS_PLUGINS_WIN_CAPTURE_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_WIN_DSHOW_MAP_DIR ${OBS_PLUGINS_WIN_DSHOW_MAP_DIR})
    string(REPLACE "/" "\\" __OBS_PLUGINS_WIN_WASAPI_MAP_DIR ${OBS_PLUGINS_WIN_WASAPI_MAP_DIR})
	string(REPLACE "/" "\\" __COD_SOURCE_DIR ${COD_SOURCE_DIR})

    add_custom_command(TARGET SoopStudio
        POST_BUILD
		
		COMMAND xcopy "${__COD_SOURCE_DIR}\\*.cod" "${__OUT_MAP_FILES_DIR}\\" /Y /I				
        COMMAND if exist "${__STUDIO_EXE_MAP_DIR}\\${STUDIO_EXE_MAP_NAME}" xcopy "${__STUDIO_EXE_MAP_DIR}\\${STUDIO_EXE_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_DLL_LIB_MAP_DIR}\\${OBS_DLL_LIB_MAP_NAME}" xcopy "${__OBS_DLL_LIB_MAP_DIR}\\${OBS_DLL_LIB_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_DLL_D3D_MAP_DIR}\\${OBS_DLL_D3D_MAP_NAME}" xcopy "${__OBS_DLL_D3D_MAP_DIR}\\${OBS_DLL_D3D_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_DLL_WINRT_DIR}\\${OBS_DLL_WINRT_NAME}" xcopy "${__OBS_DLL_WINRT_DIR}\\${OBS_DLL_WINRT_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_AJA_MAP_DIR}\\${OBS_PLUGINS_AJA_MAP_NAME}" xcopy "${__OBS_PLUGINS_AJA_MAP_DIR}\\${OBS_PLUGINS_AJA_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_COREAUDIO_ENCODER_MAP_DIR}\\${OBS_PLUGINS_COREAUDIO_ENCODER_MAP_NAME}" xcopy "${__OBS_PLUGINS_COREAUDIO_ENCODER_MAP_DIR}\\${OBS_PLUGINS_COREAUDIO_ENCODER_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_DECKLINK_MAP_DIR}\\${OBS_PLUGINS_DECKLINK_MAP_NAME}" xcopy "${__OBS_PLUGINS_DECKLINK_MAP_DIR}\\${OBS_PLUGINS_DECKLINK_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_IMAGE_SOURCE_MAP_DIR}\\${OBS_PLUGINS_IMAGE_SOURCE_MAP_NAME}" xcopy "${__OBS_PLUGINS_IMAGE_SOURCE_MAP_DIR}\\${OBS_PLUGINS_IMAGE_SOURCE_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_BROWSER_MAP_DIR}\\${OBS_PLUGINS_OBS_BROWSER_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_BROWSER_MAP_DIR}\\${OBS_PLUGINS_OBS_BROWSER_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_FFMPEG_MAP_DIR}\\${OBS_PLUGINS_OBS_FFMPEG_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_FFMPEG_MAP_DIR}\\${OBS_PLUGINS_OBS_FFMPEG_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_FILTERS_MAP_DIR}\\${OBS_PLUGINS_OBS_FILTERS_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_FILTERS_MAP_DIR}\\${OBS_PLUGINS_OBS_FILTERS_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_OUTPUTS_MAP_DIR}\\${OBS_PLUGINS_OBS_OUTPUTS_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_OUTPUTS_MAP_DIR}\\${OBS_PLUGINS_OBS_OUTPUTS_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_QSV11_MAP_DIR}\\${OBS_PLUGINS_OBS_QSV11_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_QSV11_MAP_DIR}\\${OBS_PLUGINS_OBS_QSV11_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_TEXT_MAP_DIR}\\${OBS_PLUGINS_OBS_TEXT_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_TEXT_MAP_DIR}\\${OBS_PLUGINS_OBS_TEXT_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_TRANSITIONS_MAP_DIR}\\${OBS_PLUGINS_OBS_TRANSITIONS_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_TRANSITIONS_MAP_DIR}\\${OBS_PLUGINS_OBS_TRANSITIONS_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_VST_MAP_DIR}\\${OBS_PLUGINS_OBS_VST_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_VST_MAP_DIR}\\${OBS_PLUGINS_OBS_VST_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_WEBRTC_MAP_DIR}\\${OBS_PLUGINS_OBS_WEBRTC_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_WEBRTC_MAP_DIR}\\${OBS_PLUGINS_OBS_WEBRTC_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_WEBSOCKET_MAP_DIR}\\${OBS_PLUGINS_OBS_WEBSOCKET_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_WEBSOCKET_MAP_DIR}\\${OBS_PLUGINS_OBS_WEBSOCKET_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_OBS_X264_MAP_DIR}\\${OBS_PLUGINS_OBS_X264_MAP_NAME}" xcopy "${__OBS_PLUGINS_OBS_X264_MAP_DIR}\\${OBS_PLUGINS_OBS_X264_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_RTMP_SERVICES_MAP_DIR}\\${OBS_PLUGINS_RTMP_SERVICES_MAP_NAME}" xcopy "${__OBS_PLUGINS_RTMP_SERVICES_MAP_DIR}\\${OBS_PLUGINS_RTMP_SERVICES_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_TEXT_FREETYPE2_MAP_DIR}\\${OBS_PLUGINS_TEXT_FREETYPE2_MAP_NAME}" xcopy "${__OBS_PLUGINS_TEXT_FREETYPE2_MAP_DIR}\\${OBS_PLUGINS_TEXT_FREETYPE2_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_VLC_VIDEO_MAP_DIR}\\${OBS_PLUGINS_VLC_VIDEO_MAP_NAME}" xcopy "${__OBS_PLUGINS_VLC_VIDEO_MAP_DIR}\\${OBS_PLUGINS_VLC_VIDEO_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_WIN_CAPTURE_MAP_DIR}\\${OBS_PLUGINS_WIN_CAPTURE_MAP_NAME}" xcopy "${__OBS_PLUGINS_WIN_CAPTURE_MAP_DIR}\\${OBS_PLUGINS_WIN_CAPTURE_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_WIN_DSHOW_MAP_DIR}\\${OBS_PLUGINS_WIN_DSHOW_MAP_NAME}" xcopy "${__OBS_PLUGINS_WIN_DSHOW_MAP_DIR}\\${OBS_PLUGINS_WIN_DSHOW_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
        COMMAND if exist "${__OBS_PLUGINS_WIN_WASAPI_MAP_DIR}\\${OBS_PLUGINS_WIN_WASAPI_MAP_NAME}" xcopy "${__OBS_PLUGINS_WIN_WASAPI_MAP_DIR}\\${OBS_PLUGINS_WIN_WASAPI_MAP_NAME}" "${__OUT_MAP_FILES_DIR}\\" /Y
    )
endif()
