if (WIN32)
  set(PLATFORM_DIR "${CMAKE_SOURCE_DIR}/platform/win")

  # map 파일 경로
  set(OUT_MAP_FILES_DIR "${CMAKE_SOURCE_DIR}/build_x64/mapfiles")
  set(STUDIO_EXE_MAP_DIR "${CMAKE_SOURCE_DIR}/build_x64/Release/bin/64bit")
  set(OBS_DLL_LIB_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/libobs/Release")
  set(OBS_DLL_D3D_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/libobs-d3d11/Release")
  set(OBS_DLL_WINRT_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/libobs-winrt/Release")
  set(OBS_PLUGINS_AJA_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/aja/Release")
  set(OBS_PLUGINS_COREAUDIO_ENCODER_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/coreaudio-encoder/Release")
  set(OBS_PLUGINS_DECKLINK_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/decklink/Release")
  set(OBS_PLUGINS_IMAGE_SOURCE_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/image-source/Release")
  set(OBS_PLUGINS_OBS_BROWSER_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-browser/Release")
  set(OBS_PLUGINS_OBS_FFMPEG_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-ffmpeg/Release")
  set(OBS_PLUGINS_OBS_FILTERS_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-filters/Release")
  set(OBS_PLUGINS_OBS_OUTPUTS_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-outputs/Release")
  set(OBS_PLUGINS_OBS_QSV11_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-qsv11/Release")
  set(OBS_PLUGINS_OBS_TEXT_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-text/Release")
  set(OBS_PLUGINS_OBS_TRANSITIONS_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-transitions/Release")
  set(OBS_PLUGINS_OBS_VST_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-vst/Release")
  set(OBS_PLUGINS_OBS_WEBRTC_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-webrtc/Release")
  set(OBS_PLUGINS_OBS_WEBSOCKET_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-websocket/Release")
  set(OBS_PLUGINS_OBS_X264_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/obs-x264/Release")
  set(OBS_PLUGINS_RTMP_SERVICES_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/rtmp-services/Release")
  set(OBS_PLUGINS_TEXT_FREETYPE2_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/text-freetype2/Release")
  set(OBS_PLUGINS_VLC_VIDEO_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/vlc-video/Release")
  set(OBS_PLUGINS_WIN_CAPTURE_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/win-capture/Release")
  set(OBS_PLUGINS_WIN_DSHOW_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/win-dshow/Release")
  set(OBS_PLUGINS_WIN_WASAPI_MAP_DIR "${CMAKE_SOURCE_DIR}/obs-studio/build_x64/plugins/win-wasapi/Release")
endif()